#!/usr/bin/env bash

proyecto="$1"
if [[ -z "$proyecto" ]]; then
    echo "Uso: $0 <nombre_del_proyecto>"
    exit 1
fi

proyectos="practica1 practica2 practica4 practica5"
if [[ ! " $proyectos " =~ $proyecto ]]; then
    echo "No se puede ejecutar $proyecto como aplicacion interactiva"
    echo "Opciones: $proyectos"
    exit 1
fi

./gradlew ":$proyecto:installDist" &> /dev/null || exit 1
ejecutable="./$proyecto/build/install/$proyecto/bin/$proyecto"
exec "$ejecutable"
