/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "lab-orientada-a-objetos"

include(
    ":practica1",
    ":practica2", 
    ":practica3",
    ":practica4",
    ":practica5",
    ":utils"
)
